baseURL = "https://daniel-de-oliveira-souza.github.io/TransitAnalytics/"

languageCode = "en-us"
title = "Transit Analytics"
theme = "PaperMod"

disqusShortname = 'danieldeoliveirasouza'   # use disqus comments

[params]
  # color style
  color = 'gray'                           # linen, wheat, gray, light

  # header social icons
  github = 'daniel-de-oliveira-souza'                            
  linkedin = 'danisouza1993/'               

  # home page profile
  avatar = 'danieldeoliveira1993@gmail.com'                 # gravatar email or image url
  name = 'Daniel De Oliveira Souza'
  bio = "I'm excited to share my thoughts on MTA logistics analytics and the impact of data in NYC urban planning."
