name: Deploy Hugo Site on GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Hugo Site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Hugo
      run: |
        wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.121.2/hugo_extended_0.121.2_Linux-64bit.deb
        sudo dpkg -i hugo.deb

    - name: Build Site with Hugo
      run: hugo --minify

    - name: Rename public directory
      run: mv public public_old

    - name: Clone gh-pages branch
      run: |
        git clone --branch gh-pages --depth 1 https://github.com/daniel-de-oliveira-souza/transitanalytics.git public

    - name: Copy files to gh-pages
      run: cp -r public_old/* public

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'Daniel De Oliveira Souza'
        git config --global user.email 'danieldeoliveira1993@gmail.com'
        git checkout gh-pages
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages
