name: Deploy Hugo Site on GitHub Pages

# This workflow triggers on a push to the main branch.
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Hugo Site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1
      # Ensure the compatibility with Node.js 20

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.6.0
      with:
        hugo-version: 'latest'
        extended: true
      # Check for the latest version compatible with Node.js 20

    - name: Build Site with Hugo
      run: hugo --minify
      # Builds the Hugo site with minification

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3/9/3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
      # Deploys the site to GitHub Pages
      # Ensure the GITHUB_TOKEN is set in your
